name: "Build and deploy"

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - run: bundle install
    - run: bundle exec middleman build

    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/build-push-action@v3
      with:
        file: Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ghcr.io/flatpak/flatpak.github.io:${{ github.sha }}
          ghcr.io/flatpak/flatpak.github.io:latest
        labels: |
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.source=ssh://git@github.com:${{ github.repository }}.git
          org.opencontainers.image.url=https://github.com/${{ github.repository }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
